import { PromptConfig } from "@/app/promptType";
import { z } from "zod";


const outputSchema = z.object({
    answer: z.string().describe("your answer to the question will be approx 200-400 words. Remember to use full markdown formatting, take advantage of new lines, bullet points, tables, blockquotes and any other markdown features. Do not include references to the sources in the answer in the form of referencing the source id like so  (id). Do not include source urls or titles in the answer. "),
    reasoning: z.string().describe("Explain why you decided to answer the question in this way. "),
    sourceIds: z.array(z.object({
        id: z.number().describe("The id of the source."),
        explanation: z.string().describe("The explanation for using the source. Also include how the source was used to form your answer. Include a guide to find the quote used in the source to make it easier to double check the quote."),
    })).describe("This section will be generated by a program using the id you provide to avoid hallucinations in the quotes. it is important that the ids provided match correctly to the sources."),
});
export type SectionResponse = z.infer<typeof outputSchema>;
export const prompt: PromptConfig = {
    prompt: "Act as a sales researcher presenting findings to a salesperson. here is a prompt for more information on your task: {sectionPrompt}. \n\n the following is context you will use to answer the question: {context}.\n\n you will perform the task provided in the prompt while ONLY using the information from the context. You will use quotes from the context to support your answer. You will not use any other sources. \n\n Please respond in JSON like so: {format_instructions}",
    schema: outputSchema,
};
